### ISSUE TITLE
Inferential Thinking Textbook build causes deprecation error for normed keyword

### ISSUE THREAD

**Issue by papajohn** [data-8/datascience#494] opened 2021-03-22 21:47 UTC
All the graphics (histograms & maps) on the section 8.5 page give warning messages, such as:

```
/home/choldgraf/anaconda/envs/dev/lib/python3.6/site-packages/matplotlib/axes/_axes.py:6462: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.
  warnings.warn("The 'normed' kwarg is deprecated, and has been "
```

The graphics do render.

**Comment by adnanhemani** [comment] 2022-06-05 07:25
I'm unable to reproduce this issue - and the textbook doesn't seem to have this issue either currently: https://inferentialthinking.com/chapters/08/5/Bike_Sharing_in_the_Bay_Area.html

I'm assuming it's been corrected on it's own due to some data science version upgrade?

@debbieyuster - if you still see this issue, please let me know how to reproduce (including datascience and Python versions). I'm closing this issue for now, but if you have new information, please feel free to post it here and re-open the issue :)

**Closed by adnanhemani** 2022-06-05 07:25 UTC

**Comment by debbieyuster** [comment] 2022-06-07 01:59
Thanks, looks good now!
