### ISSUE TITLE
Feature request: Shade bars in histogram to the left of a threshold

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#391] opened 2019-06-28 21:41 UTC
Ani requested this feature: when displaying a histogram, give a way to shade all of the bars to the left of a threshold one color and all of those to the right a different color.  The tricky bit: this should work even when the threshold is in the middle of a bar (i.e., the left part of the bar is shaded one color and the right part another color).

She requested this for visualizing p-values in the lectures on hypothesis testing.

**Comment by adnanhemani** [comment] 2019-07-01 06:05
Marking this as a dupe of #349. I'm transferring this text to that issue.

**Closed by adnanhemani** 2019-07-01 06:05 UTC
