### ISSUE TITLE
.group() with a list raises deprecation warning

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#458] opened 2020-09-21 17:37 UTC
If you call tbl.group(['a', 'b']), you get the following warning:

```
//lib/python3.7/site-packages/datascience/tables.py:630: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  values = np.array(tuple(values))
```

This is unsightly.  Is there anything we should/can do in the datascience library to eliminate this?

**Comment by Ipsit1234** [comment] 2020-09-26 14:11
@davidwagner You are getting this warning from [this](https://github.com/data-8/datascience/blob/97a9cb882104fba60fb03ad4dd219010f4ea6d6d/datascience/tables.py#L1422) line. I want to fix this, can I do that?

**Comment by hmstepanek** [comment] 2020-09-27 05:03
There are actually some more occurrences of this particular deprecation warning when you run the tests as well.
```
tests/test_tables.py::test_doctests
  /Users/hmstepanek/Documents/open-source/datascience/datascience/util.py:40: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
    return np.array(elements)

tests/test_tables.py: 14 warnings
  /Users/hmstepanek/Documents/open-source/datascience/datascience/tables.py:877: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
    values = np.array(tuple(values))
```

**Comment by Ipsit1234** [comment] 2020-09-27 05:06
@hmstepanek All of these warnings are of similar kind. Can I try to fix this and contribute to this open-source project?

**Comment by hmstepanek** [comment] 2020-09-27 05:16
Yes I think that would be much appreciated! (I've been contributing that last couple weeks and it's been a wonderful experience :) )

**Comment by Ipsit1234** [comment] 2020-09-27 05:23
@davidwagner @hmstepanek I am taking up this issue. Thanks a lot!!

**Comment by Ipsit1234** [comment] 2020-09-30 10:22
I made some changes locally and I ran the tests. Some of the tests were failing among which, most of them were docstring tests. The reason for failure is according to my changes, All the empty strings in a column will be replaced by `None`. But in the docstring, it is not the same case. So should I update the docstrings as well?
![image](https://user-images.githubusercontent.com/44335836/94673832-edef5580-0334-11eb-8db0-4fc57fe599e0.png)

**Comment by adnanhemani** [comment] 2020-10-01 05:27
@Ipsit1234 - were these tests failing prior to the changes you made locally? If so, then we should work with the tests available and try to craft code to make sure the tests don't fail (as they represent current behavior - which we're not looking to change).

As for this issue with `None`, I'm leaning towards keeping current functionality of making the cell blank rather than None as well. This is strictly from a pedagogical point-of-view, so if there's convincing arguments otherwise, I'd be open to discussing them here :)

**Comment by Ipsit1234** [comment] 2020-10-02 20:01
@adnanhemani no, the above tests were not failing prior to the changes that I made locally. The reason for the warning on creating an ndarray from ragged nested sequences is due to a recent change in the latest version i.e., v1.19.0 of NumPy, which discontinues the automatic inferring of the `object` datatype. The explanation for the same can be found in [NEP 34](https://numpy.org/neps/nep-0034-infer-dtype-is-object.html). 
Hence I suggest that it would be better to consider `None` instead of leaving it with empty strings as NumPy will update further in future giving the same warning again and again.

**Comment by davidwagner** [comment] 2020-10-03 08:39
I confess I don't really understand what is happening here.  It looks like in the example you gave, `marbles.group("Shape", sum)` is going to end up executing (effectively):

    c = [sum(np.array(["Green", "Blue", "Green"])), sum(np.array(["Red", "Red", "Green"]))]
    columns.append(c)

I would expect that to raise an exception.  Does it somehow get converted to `None`, and then numpy converts the `None` somehow to `"None"`?  How does that happen?  I'm not immediately seeing how we get ragged lists.

Basically, I'm trying to understand the nature of the changed behavior, under what circumstances we'd get different behavior, and how easy/hard it is to preserve existing behavior.  My bias is also towards preserving existing behavior.  I didn't quite understand the justification for displaying or storing `"None"` instead of `""`.  I don't understand the relevance of NEP 34 or why we'll continue to see warnings in the future.

Basically: @Ipsit1234, can you help me understand the root cause of what's going on?  Sorry for being dense/slow.

**Comment by Ipsit1234** [comment] 2020-10-03 11:25
I am getting this warning only when I am running the tests, as @hmstepanek  mentioned above. In normal usage, I didn't get any warning on using `tbl.group(['a','b'])` . I thought that while grouping somehow the ragged lists were forming by looking at the tests, but when I checked the code, it was not the case. 
Sorry @davidwagner for the confusion, also can you provide a code snippet to reproduce the same warning while grouping?

**Comment by davidwagner** [comment] 2020-10-03 22:17
I observed this in lec11.ipynb for Fall 2020's Data 8 demos, in the `survey.group(['Handedness','Sleep position']).show()` cell, but only on my local machine, not on datahub.  Possibly because my local machine has numpy 1.19.1 whereas datahub has numpy 1.18.5.  Let me see if I can construct a minimal reproducible testcase.

**Comment by surajrampure** [comment] 2021-03-15 05:17
Hi all! Just wanted to bump this – I get the same issue described in the original post both locally and on DataHub.

<img width="400" alt="Screen Shot 2021-03-15 at 1 16 07 AM" src="https://user-images.githubusercontent.com/10468713/111106813-29b95880-852c-11eb-833b-045da7ad89da.png">

**Comment by davidwagner** [comment] 2021-09-01 07:25
This also shows up in Chapter 8.5 of the textbook.

**Comment by langdon** [comment] 2021-09-29 21:48
For a workaround, you can add `%%capture --no-display` to the top of the cell. Obviously, YMMV.

**Comment by adnanhemani** [comment] 2022-06-05 05:39
From @davidwagner on #514 - which is a duplicate of this ticket. My next comment will explain the underlying, same issue:

> See e.g. fa21 lec10.
datascience/tables.py:920: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  values = np.array(tuple(values))
TODO: Need to create a minimal reproducible example.
Maybe related to https://github.com/data-8/datascience/issues/458.

From @langdon:
> assuming you have access to the galton.csv from data8 (could probably also be a bit more minimal)

```
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

galton = Table.read_table('galton.csv')

def predict(h):
    nearby = galton.where('midparentHeight', are.between(h - 1/2, h + 1/2))
    return nearby.column('childHeight').mean()

def difference(x, y):
    return x - y

predicted_heights = galton.apply(predict, 'midparentHeight')
galton = galton.with_column('predictedHeight', predicted_heights)
pred_errs = galton.apply(difference, 'predictedHeight', 'childHeight')
galton = galton.with_column('errors',pred_errs)
galton.hist('errors', group='gender')
```

**Comment by adnanhemani** [comment] 2022-06-05 06:13
All code paths that are showing this deprecation warning are going through this code: https://github.com/data-8/datascience/blob/master/datascience/tables.py#L999.

As @ipsitmantri explained above, this is causing the condition in [NEP 34](https://numpy.org/neps/nep-0034-infer-dtype-is-object.html) - and the deprecations have been made in Numpy 1.19.x+ AFAIK. As I don't see a reason to change any current behavior, I will be implementing the workaround mentioned in the NEP for quick relief in the next datascience release. If we have any reason to change the behavior and want some more complicated logic to determine the inner object type, then please open a new ticket with that feature request.

**Comment by davidwagner** [comment] 2022-06-09 20:57
Pull request #535 seemed to cause a bunch of tests to break, alas, so it seems we need to look at this some more.

**Comment by adnanhemani** [comment] 2022-06-12 02:05
Yup, you're right - it didn't break for me originally, but it definitely did when I tried pulling this time. I've opened a new PR #544 to solve this now. Thanks for checking!

**Closed** 2022-06-13 03:19 UTC
