### ISSUE TITLE
pathspec errors

### ISSUE THREAD

**Issue by mads14** [data-8/datascience#240] opened 2016-09-16 20:34 UTC
Hi @ryanlovett @SamLau95. A student (henryzhu) is getting pathspec errors again:
"Est. time left: 30 seconds · Status: error: pathspec 'smartcities_f16/minilabs/.ipynb_checkpoints/CE' did not match any file(s) known to git. error: pathspec 'smartcities_f16/minilabs/CE' did not match any file(s) known to git." 

Any advice on fixing this?

**Comment by SamLau95** [comment] 2016-09-16 21:24
Should be fixed now. It looks like he mixed in files from CS88 into his labs folder.


On September 16, 2016 at 1:34:52 PM, mads14 (notifications@github.com) wrote:

Hi @ryanlovett @SamLau95. A student (henryzhu) is getting pathspec errors again:
"Est. time left: 30 seconds · Status: error: pathspec 'smartcities_f16/minilabs/.ipynb_checkpoints/CE' did not match any file(s) known to git. error: pathspec 'smartcities_f16/minilabs/CE' did not match any file(s) known to git."

Any advice on fixing this?

**Comment by mads14** [comment] 2016-09-19 20:34
Hi Sam,

Sorry, another student is getting the same error. Could you look at the
account for wesleyjin12?

Thanks!
Maddie

**Comment by ryanlovett** [comment] 2016-09-19 21:48
@SamLau95 Is there a general procedure for fixing this?

**Comment by mads14** [comment] 2016-10-03 19:16
@SamLau95 I don't think wesleyjin12 was ever fixed. Do you have a fix for
me?

Best,
Maddie

**Comment by SamLau95** [comment] 2016-10-03 20:00
Oops, I missed that comment. Fixed now.

Looks like you should add a `.gitignore` file to your repo since I'm noticing many problems are caused by the `.ipynb_checkpoints` folder.

**Comment by mads14** [comment] 2016-10-03 20:07
Thanks! Will do. Also wesleyyky is getting a 502 bad gateway error. Any
suggestions on that one?

**Comment by SamLau95** [comment] 2016-10-03 22:26
Should be fixed now.

**Comment by mads14** [comment] 2016-10-10 22:19
@SamLau95, I added the .gitignore, but a student (daibyek) reported that
they just got the same pathspec error. Would you mind fixing it for me? Is
there a fix I can do after a student is getting a pathspec error?

Thanks so much for all your help!
Maddie

**Comment by mads14** [comment] 2016-10-11 04:13
A few students emailed today saying they are getting the same pathspec issue. It looks like I somehow committed some .ipynb_checkpoints that caused the issue. I have since removed them from git, but the students are still getting the pathspec error. I'm sorry to bug you with this! I'm happy to fix the issues myself instead of bugging you every time if there's a fix that I can do.

**Comment by SamLau95** [comment] 2016-10-11 05:04
Actually, there is a fix you or a student can do:

1. Visit https://data8.berkeley.edu/admin , find student who has issue
2. Click Access Server (start their server first if it's not started). This should get you into their notebook server.
3. Click New -> Terminal
4. Run `cd smart-cities-connector`
5. Run `git status`. You should see some deleted files.
6. Run `git add -A`, then `git commit -m 'Fix pathspec'`. `git` might complain about setting the username / email. You can just follow its instructions.

That should manually reset the `git` state so that pulls are possible. Let me know if that doesn't work.

**Comment by mads14** [comment] 2016-10-11 05:33
Awesome! Thanks so much! I think it worked, but i need confirmation from
the students who were getting the error. I'll let you know if there are
still issues.

Best,
Maddie

**Closed** 2017-02-05 23:58 UTC
