### ISSUE TITLE
hist.(group=...) triggers VisibleDeprecationWarning

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#514] opened 2021-09-17 16:17 UTC
See e.g. fa21 lec10.

```
datascience/tables.py:920: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  values = np.array(tuple(values))
```

TODO: Need to create a minimal reproducible example.

Maybe related to #458.

**Comment by langdon** [comment] 2021-09-29 21:44
assuming you have access to the galton.csv from data8 (could probably also be a bit more minimal)

```
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

galton = Table.read_table('galton.csv')

def predict(h):
    nearby = galton.where('midparentHeight', are.between(h - 1/2, h + 1/2))
    return nearby.column('childHeight').mean()

def difference(x, y):
    return x - y

predicted_heights = galton.apply(predict, 'midparentHeight')
galton = galton.with_column('predictedHeight', predicted_heights)
pred_errs = galton.apply(difference, 'predictedHeight', 'childHeight')
galton = galton.with_column('errors',pred_errs)
galton.hist('errors', group='gender')
```

**Comment by adnanhemani** [comment] 2022-06-05 05:36
On further inspection, this is definitely caused by the same root cause as #458. I'm working on the issue now but I'm closing this ticket and transferring the comments over to track on that ticket alone.

**Closed by adnanhemani** 2022-06-05 05:36 UTC
