### ISSUE TITLE
overlaying a scatter plot point on top of a histogram makes the histogram disappear

### ISSUE THREAD

**Issue by tbrown122387** [data-8/datascience#498] opened 2021-04-13 17:00 UTC
Some of the plotting functionality of `Table`s has been strange this semester. For example, overlaying a scatter plot point on top of a histogram either a.) messes up x-axis labels or b.) makes the histogram disappear even though the x-axis is okay. Here are some before-and-after screenshots from a student of mine.

![image (3)](https://user-images.githubusercontent.com/1740324/114590437-c6b80000-9c56-11eb-87f3-d23d984840ef.png)
![image (2)](https://user-images.githubusercontent.com/1740324/114590440-c6b80000-9c56-11eb-88fb-2582d3858b68.png)

This was on a windows 64 bit machine, and the version of `datascience` was 0.17.0. To be honest, I'm having a hard time recreating the error on my machine.

**Comment by davidwagner** [comment] 2021-06-25 00:43
Is the issue with the x-axis labels that they are truncated?

**Comment by adnanhemani** [comment] 2022-06-05 07:11
As strange as this bug report is, I'm closing it out since we've got no information for a successful reproduction. Please feel free to comment back if there's any additional information on how we can replicate the issue :)

**Closed by adnanhemani** 2022-06-05 07:11 UTC
