### ISSUE TITLE
Error terms in x-axis labels are back again

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#491] opened 2020-11-15 04:41 UTC
The issue from #347 and #311 is back again: On some datasets, the numbers on x-axis have error terms due to rounding point error (e.g., 0.1999999999999 instead of 0.2).  See the following notebook for a demonstration.

![dsbug](https://user-images.githubusercontent.com/3349841/99163043-2797d800-26b9-11eb-9065-ec9e5c1ea41c.png)

The weird thing is that `with np.printoptions(legacy='1.13'): ...` doesn't seem to work, but `np.set_printoptions(legacy='1.13')` does work.  I am not sure what is going on.

@adnanhemani any ideas what might be causing this?

See https://gist.github.com/davidwagner/75bcc524116a50a44b918c14bcaba5fa for the notebook if you want to try it on your own machine.

**Comment by adnanhemani** [comment] 2022-06-05 08:14
Umm well this was an interesting issue....took me a few hours to find a solution, although I'm not 100% sure why this is actually happening. I ended up adding `plt.show()` within the `with np.printoptions(legacy='1.13'):` block and the round error went back to expected behavior...

<img width="979" alt="Screen Shot 2022-06-05 at 3 11 58 AM" src="https://user-images.githubusercontent.com/10746770/172041727-d7bbd87f-0034-4be3-a2f9-f0f423d947ad.png">

My guess is that without explicitly calling `plt.show()` the rendering of the actual histogram has become lazy in matplotlib within the `inline` configuration and thus we are not protected by these printoptions at all since they've escaped the Python LOCs in our Jupyter notebooks. Now, by explicitly asking for rendering, we can get around this. Please let me know if you see any issues with this approach to rendering.

**Comment by adnanhemani** [comment] 2022-06-05 10:38
Never mind, this solution doesn't work - adding an overlaying plot breaks by using this approach. Looking for another solution now.

**Comment by adnanhemani** [comment] 2022-06-06 07:15
New PR opened. New approach is to manually set the printoptions when the library initializes and to throw a user warning if the user changes this property.

**Comment by adnanhemani** [comment] 2022-06-12 01:11
Closing issue as PR has been closed.

**Closed by adnanhemani** 2022-06-12 01:11 UTC
