### ISSUE TITLE
Generate shaded histograms

### ISSUE THREAD

**Issue by papajohn** [data-8/datascience#349] opened 2019-03-20 21:27 UTC
Add `left_end=...` and `right_end=...` optional arguments to `hist` so that part of the histogram can be filled in. Coloring a fraction of a bar is necessary if the ends are not on the bin boundaries.

**Comment by adnanhemani** [comment] 2019-07-01 06:06
From @davidwagner on a dupe of this issue:

"Ani requested this feature: when displaying a histogram, give a way to shade all of the bars to the left of a threshold one color and all of those to the right a different color. The tricky bit: this should work even when the threshold is in the middle of a bar (i.e., the left part of the bar is shaded one color and the right part another color).

She requested this for visualizing p-values in the lectures on hypothesis testing."

**Closed** 2019-07-23 17:34 UTC
Labels: WIP, pr-pending
