### ISSUE TITLE
`pip install` doesn't install dependencies

### ISSUE THREAD

**Issue by choldgraf** [data-8/datascience#388] opened 2019-06-27 03:38 UTC
We were just running through a tutorial on Data 8 and found that running `pip install datascience` doesn't install the dependencies needed for the datascience package. We should add the relevant parts to `setup.py` (at least, that's where I think this information lives)

**Comment by adnanhemani** [comment] 2019-06-28 12:04
This is a dupe of #335. We're working on getting the requirements.txt file completely up to date with the latest dependencies. (The requirements.txt file is read in and processed in `setup.py`). I'll make a post on that thread when we're ready with the changes. Sorry about the inconvenience!

**Closed by adnanhemani** 2019-06-28 12:04 UTC
